tlx chapter 6 B
ITDel-Programming/TLX-PD pull request #1
Opened 2020-04-24 01:58 UTC by polan1133

2020-04-24 09:18 UTC, alexandernsalim approved these changes

2020-04-24 09:43 UTC, davidtompul requested changes
--contoh minta request changes

2020-04-24 09:43 UTC, davidtompul commented on Chapter-6/polan113-B.cpp
> +	int ans = 0;
--contoh comment
ini one line aja

2020-04-24 09:52 UTC, polan1133 commented on Chapter-6/polan113-B.cpp
> +	int ans = 0;
--contoh response
ok siyap gan

2020-04-24 14:51 UTC, sihombingevita approved these changes

2020-04-24 15:39 UTC, nolan23 approved these changes
lgtm

2020-04-25 01:28 UTC, polan1133 commented
> lgtm

lgbt

2020-04-25 01:29 UTC, merged